### ISSUE TITLE
Quality control standard cannot be set in config.yaml

### ISSUE THREAD

**Issue by thomas-muench** [EarthSystemDiagnostics/piccr#16]
The option to set a standard as a quality control standard is not available in the `config.yaml` file ("set standards" section of the file). This is a needed option and also needed to harmonise the stand-alone use of **piccr** with the use from **Cpt.-Picarr**; see also EarthSystemDiagnostics/cpt-picarr#47.

**Comment by twollnik** [comment]
Good point. What exactly would piccr use this information for?

**Comment by thomas-muench** [comment]
I still owe you an update on all the quality control information stuff, which I hope I get done soon. In brief: the quality control standard is the only real independent quality control information, since, per definition, it is not used for any calibration and correction processes (or more strictly, it must not be used for these purposes). 

So as far as I see it now, piccr needs this information only for extracting the deviation of this standard from its true value, which gives us an independent control info on the entire measurement run. 

Of course, this information is available already from the `config` from the standard(s) which have no drift or calibration flag switched on. But what if a user forgets to leave one standard out from the entire correction process? Then there is no real independent control. So I would suggest to either directly include this flag in the `config`, or leave the `config` as is but to let piccr throw an error/or warning when no quality control standard is available.

What do you think?

**Comment by twollnik** [comment]
Thanks for the explanation. I think it's best to add an explicit parameter that needs to be set for all the standards.

**Comment by thomas-muench** [comment]
Closing this issue since it is resolved by EarthSystemDiagnostics/piccr#30.
