### ISSUE TITLE
Memory correction not using 'true' previous value

### ISSUE THREAD

**Issue by thomas-muench** [EarthSystemDiagnostics/piccr#18]
The memory correction relies on the true value of the previous sample via the formula

![grafik](https://user-images.githubusercontent.com/13524493/64867382-96088280-d63d-11e9-99ba-af07d329d0a9.png)

where `delta_raw^i` is the uncorrected value of the current sample for injection `i`, `m_i` the memory coefficient for this injection, and `delta_t^(i-1)` the true value of the previous sample.

For the true value of the previous sample, one can use the approximation to use the last injection, or the average of the last three injections. 

This approximation is valid for many injections, since then the last injections are nearly free of memory effect, and so is valid when calcualting the memory coefficients from standards which were injected many times.

However, it is a bad approximation for actual samples which are only injected a few (e.g. 3) times.

If I see it right, in the current implementation all samples are corrected using true previous value approximation _as calculated from the uncorrected data_ (function `applyMemoryCorrection()` -> `getDeltaTrueAndDeltaTruePrevForEachSample()`).

**Solution**:
We need an iterative approach (easiest would be a loop) to do the correction from one sample to the other.

**Note**:
I am afraid this has been wrong ever since in piccr, since in the old implementation, the correction was done using an `apply` on the rows of the data frame, which neither does update the data frame with the corrected values iteratively (as far as I think).

**Comment by twollnik** [comment]
@thomas-muench Your are right, thanks for pointing it out. Would you like me to work on this or can you do it?
