### ISSUE TITLE
Select standards for two-point calibration

### ISSUE THREAD

**Issue by thomas-muench** [EarthSystemDiagnostics/piccr#19]
In function `selectGroupsForTwoPointCalib()` the groups (desired standards) are selected by the line number in the measurement file, so that the two selected standards will be the the first and the last one being measured in the measurement sequence of the standard block. Depending on how the user has distributed the standards across the block, this selection might not cover the full range of isotope values for the calibration.

**Solution**:
I would suggest to select the two standards by grouping by mean (raw) isotope value and selecting the standards with the lowest and highest isotope value.

**Comment by twollnik** [comment]
@thomas-muench Good point. Would you like me to work on this or can you do it?
