### ISSUE TITLE
More injections of warm-up standard than any other block1 standard causes NA memory coefficients

### ISSUE THREAD

**Issue by thomas-muench** [EarthSystemDiagnostics/piccr#38]
The maximum number of estimated memory coefficients is based on the maximum number of injections of the standards in standard block 1 at the beginning of the measurement. For the very first standard in block 1 (the "warm-up standard"), no memory coefficients can be estimated, since no previous sample is available. Thus, the estimated memory coefficients for this standard are NA for all injections of this standard.

If the warm-up standard is now injected more often than any other standard in block 1, the vector of mean memory coefficients will be NA for those excess injections of the warm-up standard, since here no non-NA coefficients are available across all standards.

This is problematic, when a sample is also injected as often as the warm-up standard. Then, in the memory-correction process, all the corresponding isotope values of such a sample will be "corrected" to NA.

**Comment by thomas-muench** [comment]
To fix this, I would suggest to check if the warm-up standard has more injections than any other block1 standard. If this is the case, the data.frame of estimated memory coefficients should be clipped to the length corresponding to the maximum injection number across the block1 standards excluding the warm-up standard.

This should be implemented right within `calculateMemoryCoefficients()`.

This approach is better than just removing those rows from the data.frame which are all NA, since in the (albeit very unlikely) case that a certain injection fails for all standards, such rows could also exist _in between_ rows with non-NA coefficients, not just at the end of the data.frame.

**Comment by twollnik** [comment]
> I would suggest to check if the warm-up standard has more injections than any other block1 standard

I would leave out this explicit check. Instead I would remove all trailing NAs. E.g. if the memory coefficients dataframe looks like this 

Inj Nr | MemCoeff 
--- | ---
1 | 0.9
2 | 0.98
3 | NA
4 | 0.99
5 | NA
6 | NA

I would just remove lines 5 and 6. Example code:

```r
# variable names are made up. No direct copy paste possible
memCoeffs %>%
    arrange(desc(`Inj Nr`)) %>% 
    filter(cumall(is.na(MemCoeff))) %>% 
    arrange(`Inj Nr`)
```

**Comment by thomas-muench** [comment]
Thanks a lot for your suggestion - this is a neat solution! I will implement the fix.

**Comment by thomas-muench** [comment]
@twollnik I think your suggested solution _keeps_ only lines 5 and 6 (in your example) instead of removing them. What worked for me is

```
  # remove all trailing rows from output dataframe which only contain NA values
  memCoeffOutput <- memCoeffOutput %>%
    filter(cumall(!is.na(memoryCoeffD18O)))
```

see the respective PR.

**Comment by twollnik** [comment]
You are right that my code does not work as intended. It should be changed to

```R
memCoeffs %>%
    arrange(desc(`Inj Nr`)) %>% 
    filter(cumany(!is.na(MemCoeff))) %>% 
    arrange(`Inj Nr`)
```

(I had it like this first, but then changed it because I wanted to be clever. Turns out instead of being clever I just broke it.)

Your code does not work eather. It removes NA memory coefficients in the middle of the table. For instance in our example your code would also drop line 3.

**Comment by thomas-muench** [comment]
Ha, you are absolutely right, thanks! After having realized that your code does not do what it should, I also wanted to be clever and tried to code it myself, but, not very cleverly, did not use your example table but an own one without NA's in between... Without NA's in between both mine and your attempt work, but in the more general case _with_ NA's in between only your solution does the right thing.
