### ISSUE TITLE
Determine final standard block programatically for double calibration

### ISSUE THREAD

**Issue by thomas-muench** [EarthSystemDiagnostics/piccr#41]
For the double 2- or 3-point calibration, the calibration parameters are interpolated between the values estimated from the first and the final block of standards in the measurement file.

Since most measurement setups use three standard blocks in total, the final standard block has been hard-coded to be number 3, when obtaining the calibration parameters of the final block. 

However, to be most general, the number of the final block should instead be obtained programatically by using the maximum block number. This affects the functions `calibrateUsingDoubleCalibration()`, `getCalibTimes()` and `getCalibrationSlopes()`.

**Comment by twollnik** [comment]
Agreed!
