### ISSUE TITLE
acceptance tests

### ISSUE THREAD

**Issue by twollnik** [EarthSystemDiagnostics/piccr#8]
We should implement a set of acceptance tests that compare the results obained with the new setup to the results obtained with the old (pkg-dev) setup.

**Comment by thomas-muench** [comment]
Suggested tests to include:
* compare overall measurement quality for couple of real data files (rmsd of quality-control std) to old piccr version; test passed if rmsd is equal or lower; differentiate between d18O and dD;
* compare measurement quality for averaging first three injections between memory correction switched on or off on real data; test passed if memory correction improves quality; differentiate between d18O and dD.

**Comment by thomas-muench** [comment]
Closed by #54.
